/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

/**
 *
 * @author Mariam
 */
import Backend.Catalog;
import Backend.DifficultyEnum;
import Backend.Game;
import Backend.SolutionInvalidException;
import Backend.State;
import Backend.StorageManager;
import Backend.SudokuController;
import Backend.VerificationResult;
import Backend.Verifier;
import com.formdev.flatlaf.FlatDarkLaf;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class StartupFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartupFrame
     */
    SudokuController sudokuController;
    StorageManager storageManager;
    String sourcePath = "D:\\GitHub\\Sudoku-Game\\Defaultgame.csv";

    public StartupFrame() throws IOException, SolutionInvalidException {
        initComponents();
        this.setSize(500, 350);
        this.setLocationRelativeTo(null);
        storageManager = new StorageManager("");
        sudokuController = new SudokuController(storageManager);
        buttonGroup1.add(easyRadio);
        buttonGroup1.add(mediumRadio);
        buttonGroup1.add(hardRadio);

        easyRadio.setSelected(true);

        start();
    }

    private String chooseSourcePath() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            return selectedFile.getAbsolutePath();
        }
        return null;
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        continueGameBtn = new javax.swing.JButton();
        newGameBtn = new javax.swing.JButton();
        changeSourceBtn = new javax.swing.JButton();
        easyRadio = new javax.swing.JRadioButton();
        hardRadio = new javax.swing.JRadioButton();
        mediumRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Game");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sudoku Game Application");

        continueGameBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        continueGameBtn.setText("Continue Last Game");
        continueGameBtn.setEnabled(false);
        continueGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueGameBtnActionPerformed(evt);
            }
        });

        newGameBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newGameBtn.setText("Start New Game");
        newGameBtn.setEnabled(false);
        newGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameBtnActionPerformed(evt);
            }
        });

        changeSourceBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changeSourceBtn.setText("Change Source Game");
        changeSourceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSourceBtnActionPerformed(evt);
            }
        });

        easyRadio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        easyRadio.setText("Easy");

        hardRadio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hardRadio.setText("Hard");

        mediumRadio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mediumRadio.setText("Medium");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(continueGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changeSourceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(easyRadio)
                        .addGap(18, 18, 18)
                        .addComponent(mediumRadio)
                        .addGap(18, 18, 18)
                        .addComponent(hardRadio)
                        .addGap(138, 138, 138))))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(continueGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(easyRadio)
                        .addComponent(mediumRadio)
                        .addComponent(hardRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeSourceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeSourceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSourceBtnActionPerformed
        sourcePath = chooseSourcePath();
        try {
            start();
        } catch (IOException ex) {
            Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SolutionInvalidException ex) {
            Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeSourceBtnActionPerformed

    private void continueGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueGameBtnActionPerformed
        try {
            MainFrame mainFrame = new MainFrame(DifficultyEnum.INCOMPLETE, sourcePath);
            this.setVisible(false);
            mainFrame.setVisible(true);
        } catch (SolutionInvalidException ex) {
            Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_continueGameBtnActionPerformed

    private void newGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameBtnActionPerformed
        DifficultyEnum difficultyEnum;
        int choice = 0;
        if (continueGameBtn.isEnabled()) {
            choice = JOptionPane.showConfirmDialog(
                    this,
                    "Do you want to discard current game progress?",
                    "Warning",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
        }
        if (choice == JOptionPane.YES_OPTION) {
            if (easyRadio.isSelected()) {
                difficultyEnum = DifficultyEnum.EASY;
            } else if (mediumRadio.isSelected()) {
                difficultyEnum = DifficultyEnum.MEDIUM;
            } else {
                difficultyEnum = DifficultyEnum.HARD;
            }
            try {
                MainFrame mainFrame = new MainFrame(difficultyEnum, sourcePath);
                this.setVisible(false);
                mainFrame.setVisible(true);
            } catch (SolutionInvalidException ex) {
                Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_newGameBtnActionPerformed
    private void start() throws IOException, SolutionInvalidException {
        Catalog catalog = sudokuController.getCatalog();
        Verifier verifier = new Verifier();
        if (catalog.hasCurrent()) {
            continueGameBtn.setEnabled(true);
            newGameBtn.setEnabled(true);
        } else if (catalog.allModesExist()) {
            newGameBtn.setEnabled(true);
        } else {
            sourcePath = chooseSourcePath();
            newGameBtn.setEnabled(true);
        }
        Game source = storageManager.loadSourceGameFromPath(sourcePath);
        VerificationResult result = verifier.verify(source.getBoard());
        if (result.getState() == State.VALID) {
            sudokuController.driveGames(source);
        } else {
            JOptionPane.showMessageDialog(this, "Game provided is invalid or incomplete.", "Invalid Source Game", JOptionPane.ERROR_MESSAGE);
            newGameBtn.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    
            // Variables declaration - do not modify//GEN-BEGIN:variables
    

}
       
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
try {
            // Set FlatLaf Dark look and feel
            FlatDarkLaf.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StartupFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SolutionInvalidException ex) {
                    Logger.getLogger(StartupFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartupFrame().setVisible(true);
            }
        });
    
private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton changeSourceBtn;
    private javax.swing.JButton continueGameBtn;
    private javax.swing.JRadioButton easyRadio;
    private javax.swing.JRadioButton hardRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton mediumRadio;
    private javax.swing.JButton newGameBtn;
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

